parameters:
    app.uploads_directory: '%kernel.project_dir%/public/uploads'
    app.avatars_directory: '%app.uploads_directory%/avatars'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration explicite pour UserService
    App\Service\UserService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']