# config/packages/api_platform.yaml
api_platform:
    title: 'OnlyRoll - API VTT D&D 5e'
    version: '1.0.0'
    description: 'API pour la plateforme de jeu de rôle en ligne'
   
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
       
    docs_formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    
    # Configuration de la pagination (syntaxe corrigée)
    defaults:
        stateless: true
        pagination_enabled: true
        pagination_items_per_page: 20
        pagination_maximum_items_per_page: 100
        pagination_partial: false
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        pagination_client_partial: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']