name: Dependency Check

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at midnight
  workflow_dispatch:

jobs:
  backend-dependencies:
    name: Check Backend Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          
      - name: Check for outdated packages
        run: composer outdated --direct
        working-directory: backend
        
      - name: Security audit
        run: composer audit
        working-directory: backend

  frontend-dependencies:
    name: Check Frontend Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Check for outdated packages
        run: npm outdated
        working-directory: frontend
        
      - name: Security audit
        run: npm audit
        working-directory: frontend